// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvkfxxxiriwnfxhxupqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2a2Z4eHhpcml3bmZ4aHh1cHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NjMyMjYsImV4cCI6MjA2NzQzOTIyNn0.CTVVCz8I92AvQOKI0MBVLEz9-Y4a_UFUAdLfKpt4J2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});